# Generated by Django 5.2.6 on 2025-09-24 14:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Pool",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "Open"),
                            ("filled", "Filled"),
                            ("driver_assigned", "Driver Assigned"),
                            ("active", "Active"),
                            ("completed", "Completed"),
                        ],
                        default="open",
                        max_length=20,
                    ),
                ),
                ("max_riders", models.IntegerField(default=4)),
                ("max_wait_time", models.IntegerField(default=10)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("closed_at", models.DateTimeField(null=True)),
                (
                    "estimated_fare",
                    models.DecimalField(decimal_places=2, max_digits=8, null=True),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Driver",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("vehicle_type", models.CharField(max_length=50)),
                ("license_plate", models.CharField(max_length=20)),
                ("max_capacity", models.IntegerField(default=4)),
                ("is_available", models.BooleanField(default=False)),
                (
                    "current_latitude",
                    models.DecimalField(decimal_places=6, max_digits=9, null=True),
                ),
                (
                    "current_longitude",
                    models.DecimalField(decimal_places=6, max_digits=9, null=True),
                ),
                (
                    "rating",
                    models.DecimalField(decimal_places=2, default=5.0, max_digits=3),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RideRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "pickup_latitude",
                    models.DecimalField(decimal_places=6, max_digits=9),
                ),
                (
                    "pickup_longitude",
                    models.DecimalField(decimal_places=6, max_digits=9),
                ),
                ("pickup_address", models.TextField()),
                (
                    "destination_latitude",
                    models.DecimalField(decimal_places=6, max_digits=9),
                ),
                (
                    "destination_longitude",
                    models.DecimalField(decimal_places=6, max_digits=9),
                ),
                ("destination_address", models.TextField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("matched", "Matched"),
                            ("driver_assigned", "Driver Assigned"),
                            ("picked_up", "Picked Up"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "fare_estimate",
                    models.DecimalField(decimal_places=2, max_digits=8, null=True),
                ),
                (
                    "rider",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PoolMembership",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("pickup_order", models.IntegerField(default=0)),
                ("dropoff_order", models.IntegerField(default=0)),
                ("joined_at", models.DateTimeField(auto_now_add=True)),
                (
                    "pool",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="members",
                        to="rides.pool",
                    ),
                ),
                (
                    "ride_request",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="rides.riderequest",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Trip",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_time", models.DateTimeField(null=True)),
                ("end_time", models.DateTimeField(null=True)),
                (
                    "actual_fare",
                    models.DecimalField(decimal_places=2, max_digits=8, null=True),
                ),
                (
                    "driver",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="rides.driver"
                    ),
                ),
                (
                    "pool",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, to="rides.pool"
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="riderequest",
            index=models.Index(
                fields=["pickup_latitude", "pickup_longitude"],
                name="rides_rider_pickup__3240fb_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="riderequest",
            index=models.Index(
                fields=["status", "created_at"], name="rides_rider_status_3e479f_idx"
            ),
        ),
    ]
